title: "UBC Stat550 2021"
email: daniel@stat.ubc.ca
author: "Daniel J. McDonald"
author-url: https://dajmcdon.github.io/
description: > # this means to ignore newlines until "baseurl:"
  UBC Stat 550 - Techniques of Statistical Consulting, 2021
baseurl: "lecture-slides" # the subpath of your site, e.g.
url: "https://stat550-2021.github.io/"
remote_theme: dajmcdon/minimal-course@bootstrap



# Image and (square) dimension for logo (don't start with /)
# If commented, will use material hat theme
# logo: "assets/img/logo/SRCC-square-red.png"

# Build settings
markdown: kramdown

fixedNav: true # true or false

permalink: /:title/
markdown: kramdown
navbar: dark
theme-primary: "#6f42c1"
theme-secondary: "#fd7e14"
navbar-fixed-top: true

google_fonts: Montserrat
use-license: true

navigation:
  - title: Syllabus
    url: https://stat550-2021.github.io/syllabus
  - title: Schedule
    url: https://stat550-2021.github.io/schedule
  - title: Lecture slides
    url: https://stat550-2021.github.io/lecture-slides
  - title: Presentations
    url: https://stat550-2021.github.io/presentations
  - title: Github
    url: https://github.com/stat550-2021
    icon: "fab fa-github"
